### ISSUE TITLE
Don't pollute the global namespace (please?)

### ISSUE THREAD

**Issue by dinedal** [jcarver989/suave-charts#25]
Current behavior:
`require('suave-charts')` -> loads all the charts into `window`

What I would like:
`Suave = require('suave-charts')` -> exports everything onto `Suave`

**Comment by jcarver989** [comment]
@dinedal - currently it's loading Suave onto the window since I have to assume not all people are in a node-esque environment - but I get how that's annoying with other environments. 

With the latest commit - I've tried to make it auto detect the presence of a "module" object and if "module" is present it will avoid exporting things onto the window object. Let me know if you have any issues with that approach. 
https://github.com/jcarver989/suave-charts/commit/80f9a1c4de883bfa2c4d2e0dba2aa117a6517d67

**Comment by jcarver989** [comment]
Closing for now because I think the last referenced commit resolves this but let me know if you have further issues.
