### ISSUE TITLE
Scrollbar jump

### ISSUE THREAD

**Issue by dinedal** [jcarver989/suave-charts#26]
Current behavior:

Load basic line chart example page in Chrome, hover over point, scrollbar leaps and page wiggles.

Expected behavior:

Hovering on a point does not do this

![scrolljump](https://cloud.githubusercontent.com/assets/606028/13549792/5e93de5c-e2c2-11e5-8921-4c831797ea08.gif)

**Comment by jcarver989** [comment]
hey @dinedal  - thanks for reporting this. I was able to reproduce the scrollbar jump vertically, although I'm not seeing the tooltip show up off center from the point. 

The vertical scrollbar jump should be fixed with this commit: https://github.com/jcarver989/suave-charts/commit/4ac75da069920cf24746d1833339dabcf96ae1d4. You can grab the latest css file from master on this repo or from the downloadable zip on suave chart's website. 

If that fix doesn't resolve things on your end let me know and I'll keep looking into this.

**Comment by jcarver989** [comment]
I think this is fixed - so closing for now.
