### ISSUE TITLE
Select my axis labels for me

### ISSUE THREAD

**Issue by dinedal** [jcarver989/suave-charts#27]
I'd like a way to prevent the below from happening:

![image](https://cloud.githubusercontent.com/assets/606028/13903112/98653b36-ee29-11e5-90a9-7abdb3f7643a.png)

Basically, suave knows the draw dimensions and spacing better then I do for the chart being drawn. Given the list of labels could suave pick a label for the axis such that they are all displayed, the first and last label are for sure shown, but all the other labels are picked at the largest interval such that none of them overlap each other?

**Comment by jcarver989** [comment]
@dinedal  - there is a "ticks" option available that you can pass on the chart level. I had missed adding it in the documentation, so I'll add it there. But basically you can set that to say 10 and it will draw the first/last labels and attempt to evenly space the other 8. 

I'll set a default of 10 labels so that by default you wont hit the x labels bumping into each other.
